CREATE TABLE tareas (
    id SERTAL PRIMARY KEY,
    titulo VARCHR(255) UNIQUE NOT NULL,
    descripcion TEXT,
);

CREATE TABLE usuarios (
    id SERTAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255)UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)